import streamlit as st
st.title(":red[About Us]")
st.markdown("AI-powered CV analysis tools, such as Teal, Rezi, and CareerLab, instantly scan resumes against job descriptions to optimize for ATS (Applicant Tracking Systems) and improve hiring chances. These tools provide, on average, a score (above 80 is good), keyword suggestions, and structural improvements, usually within seconds")

st.subheader(":blue[Key Features of AI CV Analyzers : ]")
st.text("(i) ATS Compatibility Check: Ensures resume formatting and keywords pass automatic filters.")
st.text("(ii) Job Matching Score: Compares your CV against specific job descriptions for relevance.")
st.text("(iii) Keyword Optimization: Identifies missing hard and soft skills required for a role.")
st.text("(iv) Content Generation: Suggests action verbs and quantifies achievements to strengthen impact.")
st.subheader(":blue[How to Use AI for CV Analysis : ]")
st.text(" (i) Upload: Submit your resume in PDF/DOCX format.")
st.text(" (ii) Paste Job Description: Provide the job title or posting you are targeting.")
st.text(" (iii) Analyze & Refine: Review the AI’s feedback on keyword gaps and formatting.")
st.subheader(":blue[Core Components of AI CV Analysis : ]")
st.text(" (i) Resume Parsing (Data Extraction): Extracts unstructured data (PDF/DOCX) into structured information like skills, experience, and education.")
st.text(" (ii) Keyword Matching & Contextual Understanding: Goes beyond frequency, evaluating if skills are used in the correct context.")
st.text(" (iii) Job-Role Fitting (Ranking): Compares the candidate’s profile to a specific job description to compute a compatibility score.")
st.text("(iv) Actionable Feedback Generation: Provides personalized suggestions for improvement, including identifying skill gaps.")
st.subheader(":blue[Key Benefits : ]")
st.text(" (i) Efficiency: Drastically faster than manual review.")
st.text(" (ii) Objectivity: Reduces human bias in the initial screening phase.")
st.text(" (iii) Actionable Insights: Candidates receive feedback to enhance their CV for specific roles.")
st.subheader(":blue[Machine Learning and Deep Learning Approaches : ]")
st.text("(i) Recent research emphasizes the use of machine learning and deep learning models to enhance resume–job matching accuracy. Word embedding techniques such as Word2Vec and GloVe have been capture semantic relationships between skillsand job requirements.")
st.subheader(":blue[PROPOSED MYTHOLOGY : ]")
st.text("(ii) The proposed AI-Powered Resume Analyzer is a web-based intelligent system designed to automatically evaluatevide actionable feedbackce and Natural Lanniques. The system aims to  reduce manual resume screening effort, improvejob–candidate alignment, and enresumequality through data-driven insight")

